// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Questao5.Infrastructure.Database.Context;

#nullable disable

namespace Questao5.Migrations
{
    [DbContext(typeof(DbContextConfig))]
    partial class DbContextConfigModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Questao5.Domain.Entities.Business.ContaCorrente", b =>
                {
                    b.Property<Guid>("IdContaCorrente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Ativo")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("IdContaCorrente");

                    b.ToTable("ContaCorrente");

                    b.HasData(
                        new
                        {
                            IdContaCorrente = new Guid("6eb8c77b-5fa1-4681-987b-077164a8c652"),
                            Ativo = (byte)1,
                            Nome = "Katherine Sanchez",
                            Numero = 123
                        },
                        new
                        {
                            IdContaCorrente = new Guid("b1e3a0fc-0326-422a-86e0-d662ed633362"),
                            Ativo = (byte)1,
                            Nome = "Eva Woodward",
                            Numero = 456
                        },
                        new
                        {
                            IdContaCorrente = new Guid("8730e566-e2f2-42b0-b481-397c866ff5d9"),
                            Ativo = (byte)1,
                            Nome = "Tevin Mcconnell",
                            Numero = 789
                        },
                        new
                        {
                            IdContaCorrente = new Guid("4f581ad0-079d-45c3-89a9-6a62d0c81def"),
                            Ativo = (byte)0,
                            Nome = "Ameena Lyn",
                            Numero = 741
                        },
                        new
                        {
                            IdContaCorrente = new Guid("c185f76e-76c2-458b-8d8c-70d34bd0d00b"),
                            Ativo = (byte)0,
                            Nome = "Jarrad Mcke",
                            Numero = 852
                        },
                        new
                        {
                            IdContaCorrente = new Guid("83d9e1d1-01c7-4720-9edd-aa1f2067594c"),
                            Ativo = (byte)0,
                            Nome = "Elisha Simons",
                            Numero = 963
                        });
                });

            modelBuilder.Entity("Questao5.Domain.Entities.Business.Movimento", b =>
                {
                    b.Property<Guid>("IdMovimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataMovimento")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<Guid>("IdContaCorrente")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoMovimento")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<double>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.HasKey("IdMovimento");

                    b.HasIndex("IdContaCorrente");

                    b.ToTable("Movimento");
                });

            modelBuilder.Entity("Questao5.Domain.Entities.UserCase.Idempotencia", b =>
                {
                    b.Property<Guid>("ChaveIdempotencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Requisicao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("ChaveIdempotencia");

                    b.ToTable("Idempotencia");
                });

            modelBuilder.Entity("Questao5.Domain.Entities.Business.Movimento", b =>
                {
                    b.HasOne("Questao5.Domain.Entities.Business.ContaCorrente", "ContaCorrente")
                        .WithMany("Movimento")
                        .HasForeignKey("IdContaCorrente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaCorrente");
                });

            modelBuilder.Entity("Questao5.Domain.Entities.Business.ContaCorrente", b =>
                {
                    b.Navigation("Movimento");
                });
#pragma warning restore 612, 618
        }
    }
}
